//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeiXin.Lib.Core.WeiXinService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessToken", Namespace="http://schemas.datacontract.org/2004/07/WeiXin.Lib.WCF.Model")]
    [System.SerializableAttribute()]
    public partial class AccessToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Access_TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Expires_InField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Access_Token {
            get {
                return this.Access_TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.Access_TokenField, value) != true)) {
                    this.Access_TokenField = value;
                    this.RaisePropertyChanged("Access_Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Expires_In {
            get {
                return this.Expires_InField;
            }
            set {
                if ((this.Expires_InField.Equals(value) != true)) {
                    this.Expires_InField = value;
                    this.RaisePropertyChanged("Expires_In");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeiXinService.IWeiXinService")]
    public interface IWeiXinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeiXinService/GetAccessToken", ReplyAction="http://tempuri.org/IWeiXinService/GetAccessTokenResponse")]
        WeiXin.Lib.Core.WeiXinService.AccessToken GetAccessToken();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeiXinService/CreateAccessToken", ReplyAction="http://tempuri.org/IWeiXinService/CreateAccessTokenResponse")]
        WeiXin.Lib.Core.WeiXinService.AccessToken CreateAccessToken();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeiXinServiceChannel : WeiXin.Lib.Core.WeiXinService.IWeiXinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeiXinServiceClient : System.ServiceModel.ClientBase<WeiXin.Lib.Core.WeiXinService.IWeiXinService>, WeiXin.Lib.Core.WeiXinService.IWeiXinService {
        
        public WeiXinServiceClient() {
        }
        
        public WeiXinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeiXinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeiXinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeiXinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WeiXin.Lib.Core.WeiXinService.AccessToken GetAccessToken() {
            return base.Channel.GetAccessToken();
        }
        
        public WeiXin.Lib.Core.WeiXinService.AccessToken CreateAccessToken() {
            return base.Channel.CreateAccessToken();
        }
    }
}
